### ISSUE TITLE
Disable "Accept/Reject" PR button

### ISSUE THREAD

**Issue by pirateksh** [ContriHUB/ContriHUB-21#8]
Disable the "Accept/Reject" PR button in the frontend if a PR is already accepted or rejected.
This button can be found on the User Profile of a User whose role is Mentor.

Currently Assigned to @CyrilMishra

**Comment by CyrilMishra** [comment]
> Disable the "Accept/Reject" PR button in the frontend if a PR is already accepted or rejected. This button can be found on the User Profile of a User whose role is Mentor.
> 
> Currently Assigned to @CyrilMishra

pending request , it also has to be disabled ?
